# sources.yaml
allow_urls:
  - https://raw.githubusercontent.com/217heidai/adblockfilters/refs/heads/main/rules/white.txt

tier1_urls:
  - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
  - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
  - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt

tier2_urls:
  - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/ThirdParty/filter_104_EasyListChina/filter.txt
  - https://raw.githubusercontent.com/uBlockOrigin/uAssets/master/thirdparties/easylist/easylist.txt

tier3_urls:
  - https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt
  - https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt
  - https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
  - https://raw.githubusercontent.com/Filterrr/AdBlock_Rule_For_Clash/main/AD.txt
  - https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt
